### PR TITLE
[netif] allow compilation when lwIP IPv4 is disabled

### PR DESCRIPTION
**Pull request by rob-the-dude**
Some minor changes to allow compilation if you disable IPv4 support in lwIP.  I haven't done that in the committed sources, but if someone does, then they shouldn't hit roadblocks.

### CODE REVIEW

**Comment by bukepo** [comment]
@rob-the-dude I applied this patch, it fails when build with `LWIP_IPV4=0` for:
```bash
src/net/utils/nat64_utils.c:40:34: error: unknown type name ‘ip4_addr_t’
 ip6_addr_t getNat64Address(const ip4_addr_t *aIpv4Address)
```

I guess `src/net/utils/nat64_utils.c` should be guarded by `#if LWIP_IPV4`. Thoughts?

**Comment by rob-the-dude** [comment]
Well, sort of.  In my own sources, I have a modified copy of CMakeLists.txt that doesn't even add nat64_utils.c to the library sources when LWIP_IPV4 is disabled.  I suppose a potentially different (better?) change is to find the place that includes nat64_utils.h and wrap that.

For the record, I do NOT mean to imply that this commit is EVERYTHING that you need to do to build without IPv4 support -- it is not.  In fact, the demos included in ot-rtos make use of IPv4 and won't work without it.

However, if someone wanted to start building an application that did NOT use IPv4, then they would immediately run into some of these problems.  I'm trying to make the minimum set of changes that have no impact to the code when IPv4 is still enabled.  I am NOT trying to make it possible for everyone to build without IPv4 (at least not yet).

**Comment by rob-the-dude** [comment]
Actually, I looked at that, and I think it might even be easier than that.  Simply removing the inclusion of nat64_utils.h from openthread_freertos.c is really all I need.  And it turns out openthread_freertos.c no longer needs that header -- it was there from before when some of the app stuff was still in there.  mqtt.cpp, demo_101.cpp and time_ntp.cpp still need it, but with IPv4 disabled, none of those applications work anyway (so they would likely not build nor work correctly with IPv4 off).

I can back this change out and submit again with the removal in openthread_freertos.c -- it's not needed there, and that would fix my own work with no impact to the existing builds.  But again, it would not be sufficient for the existing code to build with IPv4 off -- that's substantially more work.  I'm just trying to make the changes that have zero impact to the normal IPv4-enabled case.

**Comment by jwhui** [comment]
@rob-the-dude, we generally prefer to allow inclusion of all source files regardless of build feature configuration. It simplifies those setting up their own build system (i.e. just include all source files).

That said, I think more changes will be necessary if we want to support `LWIP_IPV4=0` in the example apps as well. In particular, uses of `ip_addr_t`:
https://github.com/openthread/ot-rtos/blob/6fb5ad9417daeca88ac208ee5b8b6ffc94a6cdc2/examples/apps/demo_101/demo_101.cpp#L168
https://github.com/openthread/ot-rtos/blob/6fb5ad9417daeca88ac208ee5b8b6ffc94a6cdc2/examples/apps/demo_101/demo_101.cpp#L169
https://github.com/openthread/ot-rtos/blob/6fb5ad9417daeca88ac208ee5b8b6ffc94a6cdc2/examples/apps/test/mqtt.cpp#L180
https://github.com/openthread/ot-rtos/blob/6fb5ad9417daeca88ac208ee5b8b6ffc94a6cdc2/examples/apps/test/mqtt.cpp#L186

**Comment by rob-the-dude** [comment]
@jwhui To my knowledge, those two demo applications require IPv4 -- they make use of v4/v6 NAT to get to IPv4 services.  They're great demos, but they aren't necessary for the underlying ot-rtos platform to be useful to v6-only applications.

Requiring each demo application to support v4 and v6 seems too ambitious (certainly for me -- I personally don't have a stake in making the demo101 or mqtt examples work, or even compile, in a v6-only world).  I would, however, be willing to contribute a simple v6-only application that showed how to do that, and I'd be willing to contribute changes to the build system that provide greater flexibility for building with either.  As it stands, ot-rtos isn't usable for v6 only applications.  It's possible to make it so without making demo101 and mqtt examples work -- and that's all I was trying to make happen.  With such changes, demo101 and mqtt aren't build for v6-only cases, and therefore the changes you specify aren't needed.

Indeed, one of my complaints about ot-rtos right now is that its outermost layer tries to produce many demos (the example "make" produces many applications), rather that demonstrate how to use a platform (openthread + FreeRTOS) to let a user build their own application (here's how demo101 uses the frameworks, here's how mqtt uses the frameworks, here's a guide to using the frameworks to build your OWN application).  My own application doesn't need the external mbedTLS, or jwt, or jannson, but ot-rtos doesn't make it easy to not use them.  Is there interest in making it more modular?

**Comment by jwhui** [comment]
@rob-the-dude, yes, I think modularity is good in this case. We would gladly take contributions that improves support and demonstrate how to use ot-rtos in an IPv6-only configuration! In that case, I would be fine if other examples require IPv4.

FWIW, I do think it would be worthwhile for the existing examples to support an IPv6-only configuration (by relying on an upstream DNS64 service). However, I agree that is out-of-scope of this PR.

**Review by bukepo — APPROVED** [review]
I'm fine to merge this PR as is and further enhance the IPv6 only support with separate PRs. Thoughts? @jwhui @gjc13

**Comment by gjc13** [comment]
@rob-the-dude Will you push further changes to this PR?

**Review by jwhui — APPROVED** [review]

**Pull request merged**
